"""Actionability Scoring Engine (AHP-weighted, technique-aware).

Weights are generated by ``ahp/run_ahp.py`` (matrices in ``ahp/matrices.py``)
and stored in ``weights.json``. Field metadata (Wazuh path, OSSEM attribute,
MITRE data component) lives in ``field_metadata.py``; per-technique expected
fields live in ``technique_profiles.py``.

Scoring model:
    w_f            = category_weight x local_field_weight   (global weight)
    S_alert        = 100 x SUM(w_f * A_f) / SUM(w_f)
                     for f in the technique's expected fields
    A_f            = 1 when the field is present and non-empty, else 0
    level          = Low / Medium / High on the 0-100 actionability scale

Records with no technique profile (e.g. raw archive events) fall back to the
default profile, which covers every instrumented field.

Thresholds follow the proposal (Low < 25%, Medium 25-50%, High > 50% of the
maximum) and are kept in one place so the evaluation phase can calibrate them
with sensitivity testing.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from field_metadata import CATEGORY_LABELS, FIELD_META
from technique_profiles import get_profile

WEIGHTS_PATH = Path(__file__).resolve().parent / "weights.json"

LOW_THRESHOLD = 25.0
MEDIUM_THRESHOLD = 50.0


@lru_cache(maxsize=4)
def load_weights(path: str | None = None) -> dict:
    weights_path = Path(path) if path else WEIGHTS_PATH
    if not weights_path.exists():
        raise RuntimeError(
            f"weights.json not found at {weights_path}. "
            "Generate it with: python -m ahp.run_ahp"
        )
    return json.loads(weights_path.read_text(encoding="utf-8"))


def _get_nested(data: dict, path: str):
    """Retrieve a nested value from a dict using dot-notation path."""
    for key in path.split("."):
        if isinstance(data, dict):
            data = data.get(key)
        else:
            return None
    return data


def _level(total: float) -> str:
    if total > MEDIUM_THRESHOLD:
        return "High"
    if total >= LOW_THRESHOLD:
        return "Medium"
    return "Low"


def detect_technique(alert: dict) -> str | None:
    """Read the ATT&CK technique from mock alerts or real Wazuh alerts.

    Mock/curated alerts carry ``mitre.technique``; Wazuh alert documents put it
    under ``rule.mitre.id`` (list or string).
    """
    mitre = alert.get("mitre") or {}
    if mitre.get("technique"):
        return mitre["technique"]

    rule_mitre = ((alert.get("rule") or {}).get("mitre") or {})
    ids = rule_mitre.get("id")
    if isinstance(ids, str) and ids:
        return ids
    if isinstance(ids, list) and ids:
        return str(ids[0])
    return None


def calculate_score(alert: dict, technique: str | None = None) -> dict:
    """Calculate the technique-aware actionability score for one alert."""
    weights = load_weights()
    technique = technique or detect_technique(alert)
    profile_key, profile = get_profile(technique)
    expected = profile["fields"]

    categories = {}
    raw_score = 0.0
    raw_max = 0.0

    for category, fields in FIELD_META.items():
        category_weight_meta = weights["categories"][category]
        cat_score = 0.0
        cat_max = 0.0
        field_details = []

        for field, meta in fields.items():
            field_weight = category_weight_meta["fields"][field]
            global_weight = field_weight["global_weight"]
            value = _get_nested(alert, meta["path"])
            present = bool(value and str(value).strip())
            is_expected = field in expected

            if is_expected:
                cat_max += global_weight
                if present:
                    cat_score += global_weight

            field_details.append({
                "field": field,
                "label": meta["label"],
                "weight": round(global_weight, 4),
                "local_weight": field_weight["local_weight"],
                "rank": field_weight["rank"],
                "mitre_relationship": meta["mitre_relationship"],
                "mitre_component": meta["mitre_component"],
                "ossem": meta["ossem"],
                "expected": is_expected,
                "role": expected.get(field) if is_expected else None,
                "present": present,
                "value": str(value)[:120] if value else None,
            })

        categories[category] = {
            "label": CATEGORY_LABELS[category],
            "weight": category_weight_meta["weight"],
            "applicable": cat_max > 0,
            "score": round(cat_score, 4),
            "max": round(cat_max, 4),
            "percentage": round(cat_score / cat_max * 100, 1) if cat_max > 0 else 0.0,
            "fields": field_details,
        }
        raw_score += cat_score
        raw_max += cat_max

    total = round(raw_score / raw_max * 100, 1) if raw_max > 0 else 0.0

    return {
        "total_score": total,
        "max_score": 100.0,
        "percentage": total,
        "level": _level(total),
        "technique": technique,
        "profile": profile_key,
        "profile_name": profile["name"],
        "expected_field_count": len(expected),
        "categories": categories,
    }


def score_alerts(alerts: list) -> list:
    """Score a list of alerts and attach results."""
    return [{**alert, "scoring": calculate_score(alert)} for alert in alerts]
