import { useEffect, useMemo, useState } from 'react'
import { fetchCaseDetail, fetchTimeline } from '../api'
import TimelineView from './TimelineView'
import {
  Dot,
  EmptyState,
  KeyValue,
  LevelBadge,
  Meter,
  Panel,
  SectionTitle,
  SkeletonRows,
  TechniqueTag,
  levelTone,
  shortId,
} from './ui'

const TECH_LABELS = {
  'T1059.001': 'PowerShell',
  'T1059.003': 'CMD',
  'T1105': 'Ingress Transfer',
}

const ROLE_TONE = {
  required: 'text-accent border-accent/40',
  supporting: 'text-ink-muted border-edge',
  context: 'text-ink-faint border-edge',
}

function formatTime(value) {
  if (!value) return '-'
  return new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'medium' })
}

function buildReport(detail, timeline) {
  const { case: data, summary } = detail
  const lines = [
    `# Case report — ${data.case_id}`,
    '',
    `- Technique: ${data.technique} (${data.profile_name})`,
    `- Host: ${summary.seed?.agent || '-'}`,
    `- Seed time: ${summary.seed?.timestamp || '-'}`,
    `- Case score: ${data.case_score}/100 (${data.level})`,
    `- Required coverage: ${data.required_covered}/${data.required_total}`,
    `- Events: ${data.nodes} nodes, ${data.edges} edges`,
    '',
    '## Evidence facts',
    '',
    '| Field | Role | Weight | Q | E | Contribution | Source references |',
    '|---|---|---:|---:|---:|---:|---|',
  ]
  for (const fact of data.facts) {
    lines.push(
      `| ${fact.label} (\`${fact.field}\`) | ${fact.role} | ${fact.weight.toFixed(3)} | ` +
        `${fact.quality.toFixed(2)} | ${fact.confidence.toFixed(2)} | ${fact.contribution.toFixed(3)} | ` +
        `${fact.carriers.map((carrier) => `${carrier.source_index || '-'}#${carrier.source_id || carrier.event_id}`).join('<br>')} |`,
    )
  }
  lines.push('', '## Typed relations', '')
  for (const edge of timeline.edges || []) {
    lines.push(
      `- \`${edge.relation}\` ${edge.source} → ${edge.target} ` +
        `(confidence ${edge.confidence?.toFixed(3)}, ${edge.decision})`,
    )
  }
  lines.push('', '## Timeline', '')
  const ordered = [...(timeline.nodes || [])].sort((a, b) =>
    (a.timestamp || '').localeCompare(b.timestamp || ''),
  )
  for (const node of ordered) {
    const marker = node.id === data.case_id ? ' **(seed)**' : ''
    lines.push(`- ${node.timestamp} · EID ${node.event_id} · ${node.process || '-'} — ${node.summary || ''}${marker}`)
  }
  lines.push(
    '',
    '_Generated by actionability-scoring-dashboard. Case score = 100 × Σ(w·Q·E)/Σw over the',
    "technique's expected fields (see AHP_RESULTS.md for the weight matrices)._",
  )
  return lines.join('\n')
}

function downloadReport(filename, text) {
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

function safeFilename(value) {
  return String(value || 'case')
    .replace(/[^a-z0-9_-]+/gi, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 100) || 'case'
}

function FactRow({ fact }) {
  const carriers = fact.carriers || []
  const valueGroups = [...new Set(carriers.map((carrier) => carrier.value))].map((value) => ({
    value,
    carriers: carriers.filter((carrier) => carrier.value === value),
  }))
  return (
    <tr className="row-link">
      <td className="px-3 py-2">
        <div className="flex items-center gap-2">
          <Dot on={fact.completeness === 1} tone={fact.completeness === 1 ? 'bg-accent' : 'bg-edge'} />
          <span className="text-xs text-ink">{fact.label}</span>
        </div>
        <div className="mt-0.5 pl-4 font-mono text-2xs text-ink-faint">{fact.field}</div>
      </td>
      <td className="px-3 py-2">
        <span className={`rounded border px-1.5 py-0.5 text-2xs ${ROLE_TONE[fact.role] || ROLE_TONE.context}`}>
          {fact.role}
        </span>
      </td>
      <td className="px-3 py-2">
        {carriers.length > 0 ? (
          <div className="space-y-0.5">
            {valueGroups.slice(0, 2).map((group) => (
              <div key={group.value} className="min-w-0">
                <div className="truncate font-mono text-2xs text-ink-muted" title={group.value}>
                  {group.value}
                </div>
                <div className="truncate font-mono text-[10px] text-ink-faint" title={group.carriers.map((carrier) => `${carrier.source_index || '-'}#${carrier.source_id || carrier.event_id}`).join(', ')}>
                  {group.carriers.slice(0, 2).map((carrier) => `${carrier.source_index || '-'}#${shortId(carrier.source_id || carrier.event_id, 14)}`).join(' · ')}
                  {group.carriers.length > 2 ? ` · +${group.carriers.length - 2}` : ''}
                </div>
              </div>
            ))}
            {valueGroups.length > 2 && (
              <div className="text-2xs text-ink-faint">+{valueGroups.length - 2} more values</div>
            )}
          </div>
        ) : (
          <span className="text-2xs text-ink-faint">missing</span>
        )}
      </td>
      <td className="tabular px-3 py-2 text-right text-xs text-ink-muted">{fact.weight.toFixed(3)}</td>
      <td className="tabular px-3 py-2 text-right text-xs text-ink-muted">{fact.quality.toFixed(2)}</td>
      <td className="tabular px-3 py-2 text-right text-xs text-ink-muted">{fact.confidence.toFixed(2)}</td>
      <td className="tabular px-3 py-2 text-right text-xs text-ink">{fact.contribution.toFixed(3)}</td>
      <td className="px-3 py-2 text-2xs text-ink-faint">{carriers.length}</td>
    </tr>
  )
}

export default function CaseDetail({ caseId, onBack, onOpenAlert }) {
  const [detail, setDetail] = useState(null)
  const [timeline, setTimeline] = useState({ nodes: [], edges: [] })
  const [hideMissing, setHideMissing] = useState(false)

  useEffect(() => {
    setDetail(null)
    fetchCaseDetail(caseId).then(setDetail).catch(() => setDetail(null))
    fetchTimeline(caseId).then(setTimeline).catch(() => setTimeline({ nodes: [], edges: [] }))
  }, [caseId])

  const facts = detail?.case?.facts || []
  const topContributions = useMemo(
    () => [...facts].sort((a, b) => b.contribution - a.contribution).slice(0, 8),
    [facts],
  )

  if (!detail) {
    return (
      <Panel>
        <SkeletonRows rows={8} />
      </Panel>
    )
  }
  if (!detail.case) {
    return <p className="py-10 text-center text-sm text-ink-faint">Case not found.</p>
  }

  const { case: data, summary } = detail
  const techniqueLabel = TECH_LABELS[data.technique] || data.technique
  const maxContribution = topContributions[0]?.contribution || 1
  const visibleFacts = hideMissing ? facts.filter((fact) => fact.completeness === 1) : facts

  return (
    <div className="space-y-4">
      <button onClick={onBack} className="text-xs text-accent hover:text-blue-400">
        ← Back to cases
      </button>

      <Panel>
        {data.aggregation_provenance_truncated && (
          <div className="border-b border-sev-medium/30 bg-sev-medium/10 px-4 py-2 text-xs text-sev-medium">
            Evidence aggregation reached its per-fact sample cap; additional carrier provenance is summarized, not individually listed.
          </div>
        )}
        <div className="flex flex-wrap items-start justify-between gap-4 p-4">
          <div className="min-w-0">
            <div className="flex items-center gap-3">
              <TechniqueTag technique={data.technique} label={`${data.technique} · ${techniqueLabel}`} />
              <span className="text-2xs text-ink-faint">{data.profile_name}</span>
            </div>
            <h1 className="mt-2 truncate text-base font-semibold text-ink">
              {summary.seed?.rule?.description || 'Correlated case'}
            </h1>
            <dl className="mt-3 grid grid-cols-2 gap-x-8 gap-y-3 md:grid-cols-4">
              <KeyValue label="Case ID" mono>
                {shortId(data.case_id, 28)}
              </KeyValue>
              <KeyValue label="Host">{summary.seed?.agent || '-'}</KeyValue>
              <KeyValue label="Seed time" mono>
                {formatTime(summary.seed?.timestamp)}
              </KeyValue>
              <KeyValue label="Events">
                {data.nodes} nodes · {data.edges} edges
              </KeyValue>
            </dl>
          </div>
          <div className="text-right">
            <div className="tabular text-4xl font-semibold text-ink">{data.case_score}</div>
            <div className="mt-1 flex items-center justify-end gap-2">
              <LevelBadge level={data.level} />
              <span className="text-2xs text-ink-faint">case actionability</span>
            </div>
            <div className="mt-3 flex items-center justify-end gap-2">
              <button
                onClick={() => downloadReport(`case-${safeFilename(data.case_id)}.md`, buildReport(detail, timeline))}
                className="rounded border border-edge px-2 py-1 text-2xs text-ink-muted hover:border-accent hover:text-accent"
              >
                Export report
              </button>
              <button
                onClick={() => onOpenAlert(data.case_id)}
                className="rounded border border-edge px-2 py-1 text-2xs text-ink-muted hover:border-accent hover:text-accent"
              >
                Open seed alert
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 border-t border-edge p-4 md:grid-cols-3">
          <div>
            <div className="flex items-center justify-between text-2xs text-ink-faint">
              <span>Case score</span>
              <span className="tabular">{data.case_score}/100</span>
            </div>
            <Meter value={data.case_score} tone={levelTone(data.level)} className="mt-1.5" />
          </div>
          <div>
            <div className="flex items-center justify-between text-2xs text-ink-faint">
              <span>Required evidence</span>
              <span className="tabular">
                {data.required_covered}/{data.required_total}
              </span>
            </div>
            <Meter value={data.required_coverage * 100} tone="bg-accent" className="mt-1.5" />
          </div>
          <div>
            <div className="flex items-center justify-between text-2xs text-ink-faint">
              <span>Relations in case</span>
              <span className="tabular">{timeline.edges?.length || 0}</span>
            </div>
            <Meter value={timeline.edges?.length || 0} max={Math.max(6, timeline.edges?.length || 1)} tone="bg-ink-faint" className="mt-1.5" />
          </div>
        </div>
      </Panel>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-3">
        <div className="space-y-4 xl:col-span-2">
          <Panel>
            <SectionTitle
              right={
                <div className="flex items-center gap-3">
                  <span className="hidden text-2xs text-ink-faint sm:inline">
                    weight · quality · evidence confidence
                  </span>
                  <button
                    onClick={() => setHideMissing((value) => !value)}
                    className={`rounded border px-1.5 py-0.5 text-2xs transition-colors ${
                      hideMissing
                        ? 'border-accent text-accent'
                        : 'border-edge text-ink-faint hover:text-ink-muted'
                    }`}
                  >
                    {hideMissing ? 'Present only' : 'Hide missing'}
                  </button>
                </div>
              }
            >
              Evidence facts
            </SectionTitle>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-edge text-2xs uppercase tracking-wider text-ink-faint">
                    <th className="px-3 py-2 font-medium">Field</th>
                    <th className="px-3 py-2 font-medium">Role</th>
                    <th className="px-3 py-2 font-medium">Value / carriers</th>
                    <th className="px-3 py-2 text-right font-medium">W</th>
                    <th className="px-3 py-2 text-right font-medium">Q</th>
                    <th className="px-3 py-2 text-right font-medium">E</th>
                    <th className="px-3 py-2 text-right font-medium">Contrib</th>
                    <th className="px-3 py-2 font-medium">n</th>
                  </tr>
                </thead>
                <tbody>
                  {visibleFacts.map((fact) => (
                    <FactRow key={fact.field} fact={fact} />
                  ))}
                </tbody>
              </table>
            </div>
          </Panel>

          <Panel>
            <SectionTitle right={<span className="text-2xs text-ink-faint">{timeline.nodes?.length || 0} events</span>}>
              Case timeline
            </SectionTitle>
            <TimelineView nodes={timeline.nodes} edges={timeline.edges} seedId={caseId} />
          </Panel>
        </div>

        <div className="space-y-4">
          <Panel>
            <SectionTitle>Score composition</SectionTitle>
            <div className="space-y-2 p-4">
              {topContributions.length === 0 && <EmptyState title="No evidence facts" />}
              {topContributions.map((fact) => (
                <div key={fact.field}>
                  <div className="flex items-center justify-between text-2xs">
                    <span className="text-ink-muted">{fact.label}</span>
                    <span className="tabular text-ink">{fact.contribution.toFixed(3)}</span>
                  </div>
                  <Meter value={fact.contribution} max={maxContribution} tone="bg-accent" height="h-1" className="mt-1" />
                </div>
              ))}
            </div>
          </Panel>

          <Panel>
            <SectionTitle>Typed relations</SectionTitle>
            <div className="divide-y divide-edge/70">
              {(!timeline.edges || timeline.edges.length === 0) && (
                <EmptyState
                  title="No correlation edges"
                  hint="No related event fell inside the correlation windows — expected for very sparse or unique seeds."
                />
              )}
              {timeline.edges?.map((edge, index) => (
                <div key={`${edge.source}-${edge.target}-${index}`} className="px-4 py-2.5">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-2xs text-ink">{edge.relation}</span>
                    <span className="tabular text-2xs text-ink-muted">{edge.confidence?.toFixed(3)}</span>
                  </div>
                  <div className="mt-1 flex items-center justify-between text-2xs text-ink-faint">
                    <span className="font-mono">
                      {shortId(edge.source, 10)} → {shortId(edge.target, 10)}
                    </span>
                    <span>
                      {edge.decision}
                      {edge.delta_s != null ? ` · ${Number(edge.delta_s).toFixed(1)}s` : ''}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      </div>
    </div>
  )
}
