export function buildReport(detail, timeline) {
  const { case: data, summary } = detail
  const lines = [
    `# Case report — ${data.case_id}`,
    '',
    `- Technique: ${data.technique} (${data.profile_name})`,
    `- Host: ${summary.seed?.agent || '-'}`,
    `- Seed time: ${summary.seed?.timestamp || '-'}`,
    `- Case score: ${data.case_score}/100 (${data.level})`,
    `- Required coverage: ${data.required_covered}/${data.required_total}`,
    `- Events: ${data.nodes} nodes, ${data.edges} edges`,
    '',
    '## Evidence facts',
    '',
    '| Field | Role | Weight | Q | E | Contribution | Source references |',
    '|---|---|---:|---:|---:|---:|---|',
  ]
  for (const fact of data.facts) {
    lines.push(
      `| ${fact.label} (\`${fact.field}\`) | ${fact.role} | ${fact.weight.toFixed(3)} | ` +
        `${fact.quality.toFixed(2)} | ${fact.confidence.toFixed(2)} | ${fact.contribution.toFixed(3)} | ` +
        `${fact.carriers.map((carrier) => `${carrier.source_index || '-'}#${carrier.source_id || carrier.event_id}`).join('<br>')} |`,
    )
  }
  lines.push('', '## Typed relations', '')
  for (const edge of timeline.edges || []) {
    lines.push(
      `- \`${edge.relation}\` ${edge.source} → ${edge.target} ` +
        `(confidence ${edge.confidence?.toFixed(3)}, ${edge.decision})`,
    )
  }
  lines.push('', '## Timeline', '')
  const ordered = [...(timeline.nodes || [])].sort((a, b) =>
    (a.timestamp || '').localeCompare(b.timestamp || ''),
  )
  for (const node of ordered) {
    const marker = node.id === data.case_id ? ' **(seed)**' : ''
    lines.push(
      `- ${node.timestamp} · EID ${node.event_id} · ${node.process || '-'} — ${node.summary || ''}${marker}`,
    )
  }
  lines.push(
    '',
    '_Generated by actionability-scoring-dashboard. Case score = 100 × Σ(w·Q·E)/Σw over the',
    "technique's expected fields (see AHP_RESULTS.md for the weight matrices)._",
  )
  return lines.join('\n')
}

export function downloadReport(filename, text) {
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

export function safeFilename(value) {
  return (
    String(value || 'case')
      .replace(/[^a-z0-9_-]+/gi, '_')
      .replace(/^_+|_+$/g, '')
      .slice(0, 100) || 'case'
  )
}
